name: example
description: A new Flutter module.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter:  ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  render_metrics:
    path: ../

dev_dependencies:
  surf_lint_rules: ^2.0.0

flutter:
  uses-material-design: true
